### ISSUE TITLE
Data higher in status bar than in settings

### ISSUE THREAD

**Issue by tylerwarre** [francoiscampbell/Xposed-DataUsage#9]
On my stausbar it say I used 1.73GB but in settings it is only 1.61GB

**Comment by francoiscampbell** [comment]
Android, like most operating systems, calculates its bytes using binary multipliers (1 KB = 1024 B), but displays it using the metric prefixes (KB, MB, GB). This is technically wrong; if you're using the binary multiplier, you should show the amount using the binary prefixes, which are KiB, MiB, GiB, etc. This is what this module does. Choose those prefixes or 'Smart SI' in the settings to see the correct amount.

It seems that this has been bugging a few people lately, so I may collapse the SI and binary options into one and add a separate checkbox to use either use the SI or binary multiplier.
